# Generated by Django 5.2.17 on 2026-08-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='consultation_photos/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AI_REVIEWING', 'AI Reviewing'), ('SENT_TO_DOCTOR', 'Sent to Doctor'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('DOCTOR_RESPONDED', 'Doctor Responded'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI Assistant')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='consultations.consultationcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
