# Generated by Django 5.2.17 on 2026-08-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcase',
            name='doctor_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcase',
            name='doctor_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='ai_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
